[package]
name = "difficient"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
  "difficient-macros",
]

[dependencies]
difficient-macros = "0.1"


[patch.crates-io]
difficient-macros = { path = "difficient-macros" }
